POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email":"uppinurigouthamreddy@gmail.com",
    "device":"RMX 2030",
    "type":"google-auth",
    "image":"url",
    "name":"gouth",
    "time":"12"
}
###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "device":"samsung s23 ultra",
    "type":"username-password",
    "time":"12",
    "username":"85tj2cx4",
    "password":"0wogwca4"
}
###
PUT http://localhost:4000/users/update-user-details
Content-Type: application/json

{
    "id":4,
    "changes":[
        {
            "key":"password",
            "value":"123"
        }
    ]
}
### admin section
DELETE http://localhost:4000/admin/delete-user
Content-Type: application/json

{
    "id":3
}
###
GET http://localhost:4000/admin/all-users


### Question section
GET http://localhost:4000/questions?limit=10
###
POST http://localhost:4000/questions/add-question
Content-Type: application/json

{
    "user_id":4,
    "question":"5th question",
    "public":"NO",
    "platform":"leetcode",
    "type":"problem",
    "images":"",
    "companies":"['microsoft' , 'google', 'ibm']",
    "link":"https://",
    "postedOn":"new Date()",
    "timestamp":0
}
###
PUT http://localhost:4000/questions/change-visibility-to-public
Content-Type: application/json

{
    "id":2
}
###
PUT http://localhost:4000/questions/mark-as-incomplete
Content-Type: application/json

{
    "id":2
}

###    answers section
POST http://localhost:4000/answers/add-answer
Content-Type: application/json

{
    "question_id":1,
    "user_id":4,
    "code":"code2 goes here",
    "images":"images JSON() arraay",
    "link":"external solution link",
    "reference":"external helpful resources , separated by \n",
    "postedOn":"2025-03-23 09:24:45.120336+00",
    "timestamp":0
}
###
GET http://localhost:4000/answers/?search=code&limit=10

###
PUT http://localhost:4000/answers/update-answer
Content-Type: application/json

{
    "id":2,
    "changes":[
        {
            "key":"code",
            "value":"modified code goes here"
        },
        {
            "key":"images",
            "value":"modied images array goes here"
        }
    ]
}

###
DELETE http://localhost:4000/answers/delete-answer
Content-Type: application/json

{
    "id":1
}
###
PUT http://localhost:4000/answers/update-rank
Content-Type: application/json

{
    "id":2,
    "operation":"-"
}
###
GET http://localhost:4000/answers/get-answers-for-question/?id=1



### revise section
POST http://localhost:4000/revise/add-remainder
Content-Type: application/json

{
    "question_id":1,
    "user_id":4,
    "completed":"NO",
    "answer_id":"",
    "posted_on":"2025-03-23 13:43:58.381344+00",
    "posted_on_timestamp":1000,
    "completed_on":"2025-03-23 13:43:58.381344+00",
    "completed_on_timestamp":0,
    "priority":0,
    "email":"gouthamreddy9398@gmail.com",
    "window_size":604800000
}
###
GET http://localhost:4000/revise/get-user-remainders/?id=4
###
GET http://localhost:4000/revise
###
PUT http://localhost:4000/revise/mark-as-done
Content-Type: application/json

{
    "id":1,
    "completed_on":"2025-03-23 13:43:58.381344+00",
    "completed_on_timestamp":0
}
###
PUT http://localhost:4000/revise/mark-as-not-done
Content-Type: application/json

{
    "id":1
}
###
PUT http://localhost:4000/revise/update-task
Content-Type: application/json

{
    "id":1,
    "changes":[
        {
            "key":"posted_on_timestamp",
            "value":"123"
        },
        {
            "key":"priority",
            "value":"5"
        }
    ]
}
###
GET http://localhost:4000/revise/get-remainders-for-question/?question_id=2
###
GET http://localhost:4000/cron-job/all-jobs/?limit=2&page=0